include:
  - project: 'telecom-argentina/cio/club-personal/devops/cicd/templates'
    ref: master
    file:
      - 'Jobs/backend_jobs.yml'

# Test
test-job:
  extends:
    - .test-base
  variables:
    MODULE_PATH: "backend"
  script:
    - cd $MODULE_PATH
    - echo "Npm install from $MODULE_PATH ..."
    - npm install --prefer-offline --no-audit --progress=false
    - echo "Running unit tests from $MODULE_PATH ..."
    - npm run test:coverage

fortify-job:  # This job runs in the publish stage.
  rules:
    - if: $CI_COMMIT_BRANCH == "none"

deploy-dev:
  rules:
    - if: $CI_COMMIT_BRANCH == "none"

deploy-test:
  rules:
    - if: $CI_COMMIT_BRANCH == "none"

deploy-prod:
  rules:
    - if: $CI_COMMIT_BRANCH == "none"